@startuml FunctionPrototype
hide empty description

class Signature{
}

class NameMatcher{
}

class ArgChecker{
}

class Prototype{
	
}

class FixFinder{
}
class ArgChecker{
}



Prototype..>ArgChecker
Prototype..>FixFinder
ArgChecker-->NameMatcher
ArgChecker-->TypeMatcher
Prototype ..> Signature

@enduml