@startuml FixtureCollapser
top to bottom direction
hide empty description


state FixtureMachine {
    state entry <<entrypoint>>
    state exit <<exitpoint>>
    state c <<choice>>
    state check_for_args <<choice>>
    state "not fixture" as not_fixture : Error state
    state evalutate : exit/ iterates to next arg
    entry --> check_for_args
    check_for_args --> c : args\nleft 
    c -> recursion : Arg fixture has signature
    c -> evalutate : Arg fixture is\nsignature empty
    recursion --> evalutate
    evalutate --> check_for_args
    c --> not_fixture: arg is not\nfixture
    not_fixture -> exit
    check_for_args -> exit :  no more args
}

[*] --> entry
exit --> [*]
@enduml